Homework1
made-ml-in-prod-2021/sergey_nefedov pull request #3
Opened 2021-05-02 21:31 UTC by SergeyNefedov

Проект находится в папке `ml_project' в ветке `homework1' (1/1 балл) и имеет`` модульную структуру (2/2 балла). За основу была взята структура проекта ml_project_example: [https://github.com/made-ml-in-prod-2021/ml_project_example](url)

В качестве исходных данных для обучения модели используется датасет `heart.csv`, взятый со страницы соревнования на Kaggle: [https://www.kaggle.com/ronitf/heart-disease-uci](url)

Решается задача классификации по предсказанию наличия порока сердца у пациента (признак `target`)

Проведен EDA, результаты находятся в папке `notebooks` (2/2 балла). Были выделены две группы признаков: числовые (`numerical_features`) и категориальные (`categorical_features`). 

Для дальнейшей работы были выбраны 2 модели: RandomForestClassifier и LogisticRegression.

Для каждой модели в папке `configs` есть свой конфиг в yaml для запуска пайплайна обучения модели (3/3 балла)

Добавлен кастомный трансформер (`src/features/outlier_transformer.py`), который удаляет из датасета строки, в которых есть выбросы для числовых переменных (выбросы рассчитываются по формуле межквартильного размаха). Также в качестве аргумента можно передавать названия конкретных признаков, для которых требуется удалить выбросы (3/3 балла)

Написан пайплайн для получения предикта (`src/predict_pipeline.py`). Для примера работы берется исходный датасет, используется отдельный конфиг `predict_config.yaml`, полученные предикты сохраняются в файл csv в директории `data/predict` (2/3 балла, так как по-хорошему функция predict должна получать артефакты от обучения модели)

Написаны тесты как для отдельных модулей, так и для прогона всего пайплайна (3/3 балла). Для тестов генерируются синтетические данные, приближенные к реальным `test/data_generator.py` (3/3 балла)

Использованы логгеры (2/2 балла)

Используются датаклассы для сущностей из конфига, а не голые dict (3/3 балла) 

В файле README описано, как настроить окружение и обучить модель (3/3 балла)

В описании к пулл реквесту описаны основные "архитектурные" и тактические решения, которые сделаны в работе. В общем, описание что именно было сделано и для чего, чтобы ревьюерам было легче понять код. (2/2 балла)

Выполнены все пункты, за которые даются основные баллы, проведена самооценка (1/1 доп балл)

Итоговая оценка: 30 баллов

2021-05-08 12:12 UTC, Sergey-Pravdyukov commented on ml_project/src/data/save_dataset.py
> +def target_to_dataframe(predicts):
typing забыли.

2021-05-08 12:54 UTC, SergeyNefedov commented on ml_project/src/data/save_dataset.py
> +def target_to_dataframe(predicts):
спасибо, исправил

2021-05-08 14:30 UTC, Sergey-Pravdyukov commented on ml_project/src/predict_pipeline.py
> +def setup_pipeline_params(config_path: str):
Функция не используется.

2021-05-08 14:32 UTC, Sergey-Pravdyukov commented on ml_project/src/train_pipeline.py
> +def train_pipeline(training_pipeline_params: TrainingPipelineParams):
Функция слишком большая - не помещается на один экран. Ее стоит декомпозировать.

2021-05-08 16:36 UTC, Sergey-Pravdyukov commented on ml_project/src/train_pipeline.py
> +    logger.info(f"start train pipeline with params {training_pipeline_params}")
Логгер слишком верхнеуровневый. Такие сообщения дают понять какие этапы пайплайна прошли, какой идет в текущий момент, но информации совсем немного. Если перейти в конкретные этапы пайплайна. в коде можно найти комментарии к коду. Некоторые из них имеет смысл обернуть как сообщение в logger.info().

2021-05-08 16:44 UTC, Sergey-Pravdyukov commented on ml_project/tests/data/test_make_dataset.py
> +@pytest.fixture()
Не указан scope в fixture. Стоит добавить во все fixture.

2021-05-08 16:53 UTC, Sergey-Pravdyukov commented on ml_project/tests/models/test_models.py
> +def feature_params(categorical_features: List[str],
Точно такая же fixture есть в ./tests/features/test_build_features.py. Дублируемые fixture стоит вынести в conftest.py. Замечание распространяется и на остальные дублируемые fixture, конечно.

2021-05-08 16:58 UTC, Sergey-Pravdyukov commented on ml_project/tests/features/test_outlier_transformer.py
> +def test_outlier_transformer(test_df: pd.DataFrame):
Проверяешь только shape, но не проверяешь содержимое DataFrame'а. Добавь пожалуйста больше тестов в целом во всей работе. Сейчас вижу слабое покрытие тестами и совсем неглубокое. То есть функционал тестируется на совсем наивные вещи вроде совпадение shape'ов.

2021-05-08 17:20 UTC, Sergey-Pravdyukov commented on ml_project/tests/data_generator.py
> +def generate_test_dataframe(size: int, random_state: int) -> pd.DataFrame:
Почему бы не сделать генератор фикстурой?

2021-05-08 19:55 UTC, SergeyNefedov commented on ml_project/tests/data_generator.py
> +def generate_test_dataframe(size: int, random_state: int) -> pd.DataFrame:
Отличная идея, поправил)

2021-05-08 19:57 UTC, SergeyNefedov commented on ml_project/tests/models/test_models.py
> +def feature_params(categorical_features: List[str],
Добавил conftest.py - действительно удобная штука

2021-05-08 21:54 UTC, SergeyNefedov commented on ml_project/tests/data/test_make_dataset.py
> +@pytest.fixture()
Добавил, но если честно не до конца понял, для чего это необходимо делать. Вроде это необязательный параметр?

2021-05-08 21:56 UTC, SergeyNefedov commented on ml_project/tests/features/test_outlier_transformer.py
> +def test_outlier_transformer(test_df: pd.DataFrame):
Конкретно в данном случае кроме shape'ов проверять больше нечего. Постарался добавить еще тестов в работе.

2021-05-08 22:36 UTC, SergeyNefedov commented on ml_project/src/predict_pipeline.py
> +def setup_pipeline_params(config_path: str):
Согласен, убрал эту функцию.

2021-05-08 22:36 UTC, SergeyNefedov commented on ml_project/src/train_pipeline.py
> +def train_pipeline(training_pipeline_params: TrainingPipelineParams):
Поправил.

2021-05-09 00:17 UTC, SergeyNefedov commented on ml_project/src/train_pipeline.py
> +    logger.info(f"start train pipeline with params {training_pipeline_params}")
Добавил логгирование во все модули, аж самому понравилось как все подробно теперь стало описываться :)

2021-05-09 00:19 UTC, SergeyNefedov commented
Сергей, все замечания выше постарался учесть.

2021-05-09 21:08 UTC, Sergey-Pravdyukov commented
> Написан пайплайн для получения предикта (src/predict_pipeline.py). Для примера работы берется исходный датасет, используется отдельный конфиг predict_config.yaml, полученные предикты сохраняются в файл csv в директории data/predict (2/3 балла, так как по-хорошему функция predict должна получать артефакты от обучения модели)

Поясни пожалуйста какие артефакты должна получать функция predict в твоем понимании?

2021-05-09 21:14 UTC, Sergey-Pravdyukov commented
Работа сделана качественно,  но видно что некоторые тонкости упустил или не усвоил сразу. Отмеченные замечания были исправлены оперативно.

Все обязательные пункты выполнены.

Молодец, хорошая работа! Готов поставить окончательную оценку после выяснения вопроса о входных артефактах predict.

2021-05-09 23:29 UTC, SergeyNefedov commented
> > Написан пайплайн для получения предикта (src/predict_pipeline.py). Для примера работы берется исходный датасет, используется отдельный конфиг predict_config.yaml, полученные предикты сохраняются в файл csv в директории data/predict (2/3 балла, так как по-хорошему функция predict должна получать артефакты от обучения модели)
> 
> Поясни пожалуйста какие артефакты должна получать функция predict в твоем понимании?

Непосредственно саму модель (сериализированную), которую получили в процессе пайплайна обучения модели, чтобы заново не приходилось тратить время на обучение при предикте. Опционально какие-то дополнительные параметры самой модели (если мы делали gridsearch и хотим запомнить параметры наилучшего классификатора). И из формулировки самого задания мне показалось, что также в ходе обучения модели должна в качестве артефакта сохраняться тестовая выборка (без меток), чтобы подавать на вход функции predict для получения предсказаний. Вместо этого, как я уже написал, я использовал исходный датасет (просто для примера работы самой функции predict).

2021-05-10 10:51 UTC, Sergey-Pravdyukov commented
> Непосредственно саму модель (сериализированную), которую получили в процессе пайплайна обучения модели, чтобы заново не приходилось тратить время на обучение при предикте. Опционально какие-то дополнительные параметры самой модели (если мы делали gridsearch и хотим запомнить параметры наилучшего классификатора). И из формулировки самого задания мне показалось, что также в ходе обучения модели должна в качестве артефакта сохраняться тестовая выборка (без меток), чтобы подавать на вход функции predict для получения предсказаний. Вместо этого, как я уже написал, я использовал исходный датасет (просто для примера работы самой функции predict).

Планируешь это исправлять или я закрываю домашку?

2021-05-10 13:57 UTC, Sergey-Pravdyukov requested changes
Смотри предыдущий комментарий.

2021-05-10 14:08 UTC, SergeyNefedov commented
> Смотри предыдущий комментарий.

Да, я сейчас пытаюсь это исправить, но возникает следующая проблема: в тестовой выборке ведь могут не все категории попасть, которые были в исходном датасете. Из-за этого при вызове предикта уже заранее обученная модель ожидает, что фич будет больше. Получается, нужно еще сам трансформер обученный, который получился во время пайплайна обучения модели, тоже сохранить как артефакт и передавать его на вход функции predict? А что если в тестовую выборку попадут новые данные (новые категории) - тоже возникнет проблема тогда. Поэтому если брать исходный датасет, то проблем не возникает :)

P.S. Думаю, можно закрыть домашку, если за этот момент только 1 балл будет снижен. Но хотелось бы для себя разобраться все-таки, как можно исправить эту проблему.

2021-05-10 14:16 UTC, Sergey-Pravdyukov commented
> ...но возникает следующая проблема: в тестовой выборке ведь могут не все категории попасть, которые были в исходном датасете. 

Приведи пожалуйста простой пример, я ничего не понял.

2021-05-10 14:26 UTC, SergeyNefedov commented
> > ...но возникает следующая проблема: в тестовой выборке ведь могут не все категории попасть, которые были в исходном датасете.
> 
> Приведи пожалуйста простой пример, я ничего не понял.

Например, в исходном датасете был категориальный признак со следующими значениями: ["1", "0", "2", "1"], после OHE получится 3 фичи для каждой категории. А в тестовой выборке попадут только следующие значения: ["1", "0", "1"], и если трансформер обучать только на этой выборке, то получится уже 2 фичи, а не 3. И модель будет ругаться, что ожидает 3 фичи, а тут только 2. Или другой пример: в тестовой выборке значения ["0", "1", "2", "3"] - получится уже 4 фичи вместо 3.

2021-05-10 14:39 UTC, Sergey-Pravdyukov commented
> > > ...но возникает следующая проблема: в тестовой выборке ведь могут не все категории попасть, которые были в исходном датасете.
> > 
> > 
> > Приведи пожалуйста простой пример, я ничего не понял.
> 
> Например, в исходном датасете был категориальный признак со следующими значениями: ["1", "0", "2", "1"], после OHE получится 3 фичи для каждой категории. А в тестовой выборке попадут только следующие значения: ["1", "0", "1"], и если трансформер обучать только на этой выборке, то получится уже 2 фичи, а не 3. И модель будет ругаться, что ожидает 3 фичи, а тут только 2. Или другой пример: в тестовой выборке значения ["0", "1", "2", "3"] - получится уже 4 фичи вместо 3.

А если разделить датасет после трансформера?

2021-05-10 14:47 UTC, SergeyNefedov commented
> > > > ...но возникает следующая проблема: в тестовой выборке ведь могут не все категории попасть, которые были в исходном датасете.
> > > 
> > > 
> > > Приведи пожалуйста простой пример, я ничего не понял.
> > 
> > 
> > Например, в исходном датасете был категориальный признак со следующими значениями: ["1", "0", "2", "1"], после OHE получится 3 фичи для каждой категории. А в тестовой выборке попадут только следующие значения: ["1", "0", "1"], и если трансформер обучать только на этой выборке, то получится уже 2 фичи, а не 3. И модель будет ругаться, что ожидает 3 фичи, а тут только 2. Или другой пример: в тестовой выборке значения ["0", "1", "2", "3"] - получится уже 4 фичи вместо 3.
> 
> А если разделить датасет после трансформера?

Да, так работает. Но я думал, что в качестве тестовой выборки все-таки берется часть исходного датасета, а не после применения трансформера. И это все равно не решит проблему, если в тестовой выборке окажутся новые категории, которых не было раньше в исходном датасете.

2021-05-10 15:41 UTC, SergeyNefedov commented
> > Непосредственно саму модель (сериализированную), которую получили в процессе пайплайна обучения модели, чтобы заново не приходилось тратить время на обучение при предикте. Опционально какие-то дополнительные параметры самой модели (если мы делали gridsearch и хотим запомнить параметры наилучшего классификатора). И из формулировки самого задания мне показалось, что также в ходе обучения модели должна в качестве артефакта сохраняться тестовая выборка (без меток), чтобы подавать на вход функции predict для получения предсказаний. Вместо этого, как я уже написал, я использовал исходный датасет (просто для примера работы самой функции predict).
> 
> Планируешь это исправлять или я закрываю домашку?

Исправил. Думаю, можно теперь закрывать.

2021-05-10 15:49 UTC, Sergey-Pravdyukov commented
> > > > > ...но возникает следующая проблема: в тестовой выборке ведь могут не все категории попасть, которые были в исходном датасете.
> > > > 
> > > > 
> > > > Приведи пожалуйста простой пример, я ничего не понял.
> > > 
> > > 
> > > Например, в исходном датасете был категориальный признак со следующими значениями: ["1", "0", "2", "1"], после OHE получится 3 фичи для каждой категории. А в тестовой выборке попадут только следующие значения: ["1", "0", "1"], и если трансформер обучать только на этой выборке, то получится уже 2 фичи, а не 3. И модель будет ругаться, что ожидает 3 фичи, а тут только 2. Или другой пример: в тестовой выборке значения ["0", "1", "2", "3"] - получится уже 4 фичи вместо 3.
> > 
> > 
> > А если разделить датасет после трансформера?
> 
> Да, так работает. Но я думал, что в качестве тестовой выборки все-таки берется часть исходного датасета, а не после применения трансформера. И это все равно не решит проблему, если в тестовой выборке окажутся новые категории, которых не было раньше в исходном датасете.

В целом если случается такая ситуация, то проблема не в разработчике, а в данных с которыми он работает. Здесь есть два пути решения:
  1. Намайнить еще данных
  2. Добавить синтетических данных в достаточном количестве

2021-05-10 15:54 UTC, Sergey-Pravdyukov approved these changes
Отличная работа! 31 балл.

2021-05-10 15:59 UTC, SergeyNefedov commented
> Отличная работа! 31 балл.

Спасибо за ревью!

2021-05-11 19:14 UTC, Sergey-Pravdyukov commented
Привет, @LuckyAndre!

Напоминаю правила ревью Михаила и призываю к действиям!

> Про ревью друг друга:
Когда вас добавили в ревью, посмотрите код коллеги, напишите свои замечания, если что-то по вашему мнению сделано не очень хорошо, что можно в этом коде улучшить, если видите особенно клевый участок кода, то можно похвалить автора=) И не стоит себя недооценивать! Далее напишите, какому кол-ву баллов по вашему мнению соотвествует работа и почему бы вы лично что-то сняли. 
 Если вас назначили и вы НЕ БУДЕТЕ делать ревью, смотреть код принципиально, то удалите себя из ревьюеров и добавьте students заново(выберет другого)
 Если решили покинуть курс(не сдавать домашние работы), то заполните форму, я удалю из организации и вы не будете попадать в ревьюеры. (не вводите ники друг друга, это жестко!)

2021-05-13 02:09 UTC, LuckyAndre approved these changes
Все основные замечания были устранены. Извиняюсь за задержку с ответом.

2021-05-13 20:14 UTC, Mikhail-M commented
Мерджим в мастер

2021-05-13 20:18 UTC, merged